export enum PageCode {
    TOUR = 'TOUR',
    TOUR_FORM = 'TOUR_FORM',
    TOUR_BOXES = 'TOUR_BOXES',
    TOUR_DESCRIPTION = 'TOUR_DESCRIPTION',
    TOUR_DAY_DESCRIPTION = 'TOUR_DAY_DESCRIPTION',
    TOUR_CALENDAR = 'TOUR_CALENDAR',
    TOUR_GALLERY = 'TOUR_GALLERY',
    TOUR_GALLERY_PREVIEW = 'TOUR_GALLERY_PREVIEW',
    TOUR_TYPE = 'TOUR_TYPE',
    TOUR_CATEGORY = 'TOUR_CATEGORY',
    COMPANY = 'COMPANY',
    COUNTRY = 'COUNTRY',
    CITY = 'CITY',
    DISTRICT = 'DISTRICT',
    ACTIVITY = 'ACTIVITY',
    ACTIVITY_FORM = 'ACTIVITY_FORM',
    ACTIVITY_DESCRIPTION = 'ACTIVITY_DESCRIPTION',
    ACTIVITY_GALLERY = 'ACTIVITY_GALLERY',
    ACTIVITY_GALLERY_PREVIEW = 'ACTIVITY_GALLERY_PREVIEW',


}
