export enum PageCode {
    TOUR = 'TOUR',
    TOUR_FORM = 'TOUR_FORM',
    TOUR_BOXES = 'TOUR_BOXES',
    TOUR_DESCRIPTION = 'TOUR_DESCRIPTION',
    TOUR_DAY_DESCRIPTION = 'TOUR_DAY_DESCRIPTION',
    TOUR_CALENDAR = 'TOUR_CALENDAR',
    TOUR_GALLERY = 'TOUR_GALLERY',
    TOUR_TYPE = 'TOUR_TYPE',
    TOUR_CATEGORY = 'TOUR_CATEGORY',


}
